dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm run build
deploy:
  provider: s3
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: factor-ui
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_ID
  -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
env:
  global:
  - secure: CjwYU+lu7OIzR7HaBpL+6bzcK9vUiUOISp+w4HbasqnlAOoQ49KeWvElhGb3Qkk+tlqiMyHWbitq4tXYd1WGC71o89kDL+QyKTaRAHBDFEg8OohKVPzDIQxFWTVTrBi1xAkNRe29H5xdewmDCaZ6cxv7ccIfGHNgwaMzjOFnpA6QfFBbnmKxvmJx3rDRlraDfRWT/KaPigjwC/P7+X18kZpsfWGEkHF0n4NZbn2DWqkqM//HV+G3+AdXmPx35JpAfB+ycEETvAEaWhMZJbUM0DqlmRRZ/IcYa+a4AK9O2GsUk4JRNEzCK6l8v8i+1hxuOALDjIOpzCWA/lEEHo8sgCMgPD2Uif8P/t/z1qqwkVjJ9jo3aHEIIZVxsRWPJyWdaw8I1MtIg76aEzlgVNEsrlycinZ08K/LKK+4udOaEDiClNHrz0J2mT57vsmSZE5GNtBa9hOqhWMubMdm2crWDSb/CQ5soAM3/zQ6YzO9XCKVEq1OXEQQFcZpVUIm4+0bAIpVR0W7abK4ilLjRW2OxVChXDZSTJanLu60BdxUTKXJvdSjNQbYmBQK2A2TkKxJIF6czH0vZ0iUduyh1CTfE4j0i3EqKYSifXu9d+jJcISmDXwUJytH5oVNQ0Axtsjyr0rdYhKN2fwMdrsE8KPPjVYL+LNPYLJrEBJuzImnvoY=
  - secure: jZG9lkDaQWOxz/5+bw0unUYL/2UouQ3q1mNL+Buy7sSHKuAEYSOweVVDLh5ZDQF5zKkZlJQCM7k/1s8GUQVP23tRiCAbVIah5ZjP3i/karrjFgpkewtRqn3AkMdZ6AU4/7R7GDMy84rnir2h6ZgoW3PJtk6Kw8JJrer/jyL3QBkSGNXAvBhWRat0jhedM+ZqldxA3cJH52OMoYjJ4XlW0FVAMAZagqsrNVtG72WSj9pydhVuBH5IqBWHIsym04NkRP+dY3dyyH6x5ZGGSGBhvA/m7mYs8YMbzloNua4iwv9sf0OjPzW7HzNO0010emkzkeLaMIRw5A96SJXi3kP7Qg/7isRE4nbWoTs6F5PaIvlKO7+6uROg4dk2BZirtxHwDNhh2u2w/KcaKeniQbiPU/uImY/4UmavnZBg5zP8XP+R+mDc0qB0Manyqsy54Ux1cv3dSgeS8Yy4sebcYb3/2PraFwAzRzxF1XfELHKMn2xPLQwQ1EPu/zBVnWQVSD7JxToeF2NZEflCagN1Ts4h3imkviCN53NfKay4OtjIbKhedxc3T7m17G2Nt1BM63oTh3SFCy8lL3lWObm4tEbAtYPy1ZKe4PZRcJ+t0/ttlwDWGdkV4ypbs7hvbYtv6viOGSrNWrtfHntNnHbKvMSf0eOuz+ZhtL9cesJ/QUtwAU4=
  - secure: iLYJNQnpipV4Q5RNjoQEZVJAwO15rIoYBX53cbrb6hKWgtUrKU/Q4IXeIqVRRWM/U2runQDkkFt4AsvuwcTAEfjMoanscaKI1d4ZakCta+8Zeb/u0NHc7rjiKj1z9vWsBUxXW9flBa6ivBhDjpAx3FYj4kNdwSdQ//SVv+8PFE+HjxG/Gv787GA0EyfxXy/VlSl+kCe1CnqntqsFLNMLl4i9ZUSmX92Mg3wf8jswkTzKiHWceM5ZZqVhSLig6kAxtb610MsWUNpTsIPFnnk2QMtASnmxYnJrjIpwjxMLtjVYq3YROA6PILT4ulEQL61KhHm2ugNa/esHdDx3ZCIPyDw2uVLiohipB24Udf9v7tSnbulLWLlE26ShIHFKtVGpcsI6vesd6V1M7ME2YxoHoLGwtmniP/HWT1NPVpiWXCBEsRapeYz9u1qaPuifsin+VJ4JEdVK1YOyBLKGmS0w2Ye9vfeUcWz7gXeo9jhTX1dKfi1NfYmWmfKkTInURhtlkGyN3bcRCmYNld8JkZ3l5Lc2sFgLlhXr16dwcahGYZHoWzVhyHgDvfzo5t1BjWpRRvNKjctsZOQIEbm7YdfltQyvkES1II841UUGmYYhptDkaLkMWS57f2Wzmw6toSXwk0fCjYL7q8bn6cL9D7Fx76koptp+SCpJ0nQshQxq7+E=
  - secure: h+2tbuI5uQpxu+OBBKCSEZym/01O47FIIujGn13JJQ3Vv5oeaLqwikgdvLJTwlV+3BOIdrC+m3iQCWkFYSNrFZKNCb+KCKDpFzKKF2pXXs9Zb1hefjftS9rdkSDYxgZfNtoiNxaB9jc+oH/qsRdCy0WWwHAFSK/T0fuNoPbe6McNcNe2Qkj8BdnF5IPlNzC6dTWtTI1Q4318y96oVHRQWLu+CRjPDnlBOCd/q7FMuwBzDk7lx3l/61jajGrAUrKm+ZnnuP4Wu2Z5Skw8+BcmFIGbBywTlsSUEgAqYs24isACusKcj1fvyd36ERIowemu3604Xa5ydpNBiZ5E9AZOP709zdNa2hVdm3zOf8Icc65hZMpJC9O9Jow1J9PDe9Ez9Dk/Mu4t6dDFO3mCLU4+S9qJmzNNl39KsoypV3+a7mNxztVFN68EAZnUoetDzYrlJmX+dKNqFNwxCT3sM/A3ImAugoRHyg5VwOKF2n9Yn962gNeVxtinbhb+dtUz7hkpT7wfXgds6vi/13ILQyTlmU10vUg+3V1QQ5wIVzt4zAna0WBaW7LwEqaIH5JmBugEM768jLRheBXHTC2cyB9RdRWCuP22YiPWi4PxcJDYhXXUyztdy1nSrciqQASzO1DcSTEpGWOnX+6Pamnfjh8SYhgEo0xLhnxc+XVvimz7fL0=
