dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm run build
deploy:
- provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: factor-ui
  local_dir: dist
  skip_cleanup: true
  on:
    branch: feature/add-provider
env:
  global:
  - secure: SebsYFVB/1/thugeIR01VpFAk8ZLrIygjouOQzuQt5dpYffUAE4Jpc8LWGv7bCQgc6fokpDu2sKkNKrs+C97gvOCnQ+Bv5LtLqe2aT0rBEDJrEM9A3TYK3EEDI6mTOSoSG9L4Q+Zg4dJkjFcMSi9ZxU7tHSUHSl8j2Si3/oACKeYWvRJQquHMMH843mlEQX0HOp1XnX1j8Azh0lzccqJcZyzNnRGL7FexFJCjVCEY9h3v2dYxBn6AyuUfYKEP3AmD0jXTmKTiJtidaw5JCb4rPRbV0bA1Soa4BfadOGeiVBAsqZewyIunIWvV9p8gM7sf4pddO7eVh6HRPh+t7LO3jMvxnsyBIHF8XgIndpb+Xk/q6GAnDQKo/FtslcFpnCvo5gK+n367yyrFRBbLOxmhuJtIor04aXAeivxVuepTo1h28ldfyEp9iNQ5TXTEucMPTzXU23TNejP2BauR5K+f/RQocZQLKC+Zd2dG0WdRILn7YuwW4DACemuszD/3obDdnamHxEbOsKKUDlXq9a8F8YQpcrNR9lZ+hUo/AsmK1qxjPuoYf4cZ9N5Lycs6/jjkgNBR67w+YOrF8YznLXgUY5U3O1XHsYRjsCthlK1CzLmFO6D2qkcFXWqn5RSxCAXxxoIL+VrHsFX4rwjbJhmetoiP/OhI1Wwh8HS0x9bxFA=
  - secure: HnsDxA7TxKn9jOS52Taad5CHmSflCIpcPTaWiDjlgsUUxdApVwgfcGWkGIxLbtPAyZaAy1h1C1/+NNB2ccF7xpvf2C23MqRWdh6a17NHqTl0f0iSI2N/oEvJYFoZSzjCJJIggulSevfJZF9MrRhdBMT2hU2wAy1oY3FRQr5pmML5JdSIls+RmBYnTmsNb7WK1UJb4wl/lpqiYqMYoemRw/ZvCWsxgBV14bEgU7JfnoJC1BoD4PSNtrJorzpLLPas/ZkNr1XzxcsMJcXM2eysowdl4d4n6jjWA9r+fcyHpNE/N7wfvXtz47fxBdaPQbYPa+ivJ8kOKh4Ve+pXf4XE1YzkprECfMknbFLBGT5Ci/XZnWKqYdG+hzgn12dekjYBvd63XxwWDdLJJZ3lW4pvsM7Ht/0secpgzyw35XkjJH1/iFPABJ0xEjT42MMG12HPUnRhVk5BSQYC201Ftjc2Rzy9+DhanTE7nvyElwllhklbiC7BCnUzq+R8wKmVJ0iX9/hxfqZkxZ6uuqVWJzA+Q1ta447bHD2a3WkjOcFpcawFjzL4km2FjI+Im+uWLbFltO9Ppu3vvWp0Ap6pcBqtDJK8klOw84OooSh+xoIbvGf/R6mkZVnXFOVTpAi2KzEsS/u4wmKyl9Thy5a0WvN7BuiCgQchqohcfst/XMI9HDk=
