dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_AUTHORIZATION_TOKEN"
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_ID"
  secret_access_key: "$AWS_SECRET_ID"
  bucket: factor-ui
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
after_deploy:
- travis-ci-cloudfront-invalidation -a $AWS_ACCESS_ID -s $AWS_SECRET_ID -c $CF_ID
  -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
env:
  global:
  - secure: hWI/20xOJLVTZgIqXC12i7jcpwTl1opc+0bJ3zRGY3tGsfP1GVIqVSRmHtyYeOsYLhmtncTzKrSf1zkbl1EBOmR9E8IlbU0/s/aDFM7CiCLma2rW4QyKkR6u12a31Z4GoPLv9KZAe5GGn1TW6Oeu3oKYc4aC0Mwk3IgOXXCfbV73zn8jaQi+OwRSN5CbE47MciQMMznVJJFMdObSiuBICsjmkRWOfVQ63U6R0lAYv4sQn0emC3i5XwuJVFq1i+fOtHmgZmj+CUGj3v5InUdfnGziwm/w17eFr09oGE3qEIpHau8ow6MGU4Ph9gmR6zt1VpT4eggb6vxZNt451jmhKjtIjIH6iBs0K2CDVp0tCn18kRTyHpiPGLlNVT6kaBVwPPc/+Vzt0kcCT4V9Tt+VGvVJvw3Cvq07McnwbdLIi611lF9dxliZNsWpFPsFHJpbnn9Kp8yIxXGUo0MxiDw6AxeldAINqrT0b0e28W1lHXB7IvNO/EycUyOI/C+GYQjKJ/RNSrSZS4XVFk7vCIaQVwBuAYP9h5peyGfdtDLctbvQrQIjJf9RtUiEVycze3ee3d2hk3ntHMmagI/TGWaLZMQ1VIPZxzveH4WhgJFPBxIsW2bPPM0UF4QYNSvr7WK4ZGaCuvJT5FjqRN8xfszwYsUIqk2q4f67jeJA8LPiexw=
  - secure: DcuJzevWZ4IEMopcqS7eFNLdO5VGFqCXOvgX4VaJFlbp9va0Oznb/iMgxnSSMGLrREQ7RDg2KBFW1qKqskNfFNCIl0z/vYTjKkrerCDhAfWa7Y9huveIASSj1oUeVm8MKbdNVwRl90kxwRM7tAHBGqazLwtf1wugMaRGHignKA1MTyhftm+eZMeVbELfyf/7uFhBZsd+SG+Nn/0zQmwjh/lph3eZ44zKQu1UI61KkZ4+owT6fZoawAyNoDejm8Mca/X6azFfIxsmq1sIO55VvwXdLSnSRB2NI4c5uERoJ3zor8rEAlfLzJtZcnBL5uUV3Xpj7domdzUVCKDOG2Rufa598wt/MEY42RoG4fUeYvO9ZY8gsYmVOwin96C5mtuBrgzhxhYguMMkKvKFuSd2ler4sARrSGV61zSgVMiK6Corc5OAsQHcdS3WZUsM+79pefeoWRy3f68DzAfD7p7eI7xFoEo5kxNUM1l1O2HJZgKvtglokMOx+K2E5VpKGOwCm0TOCW4btjd65QEAwKc0OFup11RAfp4UzjM/5it109JC8q3iYMSwKLUoq2dnzgRj1etMM3SmqC3zYC+tpywWpnsEqgY5mWwhKlIkrZ1FqnfuRFiwHePlFOdcSF1XD82y4yNO7D4m5HG4iMCX8UAuXDv1aGnCLw0MvLyvMpImnnw=
  - secure: CjwYU+lu7OIzR7HaBpL+6bzcK9vUiUOISp+w4HbasqnlAOoQ49KeWvElhGb3Qkk+tlqiMyHWbitq4tXYd1WGC71o89kDL+QyKTaRAHBDFEg8OohKVPzDIQxFWTVTrBi1xAkNRe29H5xdewmDCaZ6cxv7ccIfGHNgwaMzjOFnpA6QfFBbnmKxvmJx3rDRlraDfRWT/KaPigjwC/P7+X18kZpsfWGEkHF0n4NZbn2DWqkqM//HV+G3+AdXmPx35JpAfB+ycEETvAEaWhMZJbUM0DqlmRRZ/IcYa+a4AK9O2GsUk4JRNEzCK6l8v8i+1hxuOALDjIOpzCWA/lEEHo8sgCMgPD2Uif8P/t/z1qqwkVjJ9jo3aHEIIZVxsRWPJyWdaw8I1MtIg76aEzlgVNEsrlycinZ08K/LKK+4udOaEDiClNHrz0J2mT57vsmSZE5GNtBa9hOqhWMubMdm2crWDSb/CQ5soAM3/zQ6YzO9XCKVEq1OXEQQFcZpVUIm4+0bAIpVR0W7abK4ilLjRW2OxVChXDZSTJanLu60BdxUTKXJvdSjNQbYmBQK2A2TkKxJIF6czH0vZ0iUduyh1CTfE4j0i3EqKYSifXu9d+jJcISmDXwUJytH5oVNQ0Axtsjyr0rdYhKN2fwMdrsE8KPPjVYL+LNPYLJrEBJuzImnvoY=
  - secure: jZG9lkDaQWOxz/5+bw0unUYL/2UouQ3q1mNL+Buy7sSHKuAEYSOweVVDLh5ZDQF5zKkZlJQCM7k/1s8GUQVP23tRiCAbVIah5ZjP3i/karrjFgpkewtRqn3AkMdZ6AU4/7R7GDMy84rnir2h6ZgoW3PJtk6Kw8JJrer/jyL3QBkSGNXAvBhWRat0jhedM+ZqldxA3cJH52OMoYjJ4XlW0FVAMAZagqsrNVtG72WSj9pydhVuBH5IqBWHIsym04NkRP+dY3dyyH6x5ZGGSGBhvA/m7mYs8YMbzloNua4iwv9sf0OjPzW7HzNO0010emkzkeLaMIRw5A96SJXi3kP7Qg/7isRE4nbWoTs6F5PaIvlKO7+6uROg4dk2BZirtxHwDNhh2u2w/KcaKeniQbiPU/uImY/4UmavnZBg5zP8XP+R+mDc0qB0Manyqsy54Ux1cv3dSgeS8Yy4sebcYb3/2PraFwAzRzxF1XfELHKMn2xPLQwQ1EPu/zBVnWQVSD7JxToeF2NZEflCagN1Ts4h3imkviCN53NfKay4OtjIbKhedxc3T7m17G2Nt1BM63oTh3SFCy8lL3lWObm4tEbAtYPy1ZKe4PZRcJ+t0/ttlwDWGdkV4ypbs7hvbYtv6viOGSrNWrtfHntNnHbKvMSf0eOuz+ZhtL9cesJ/QUtwAU4=
