dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm run build
deploy:
- provider: s3
  access_key_id: "$access_key_id"
  secret_access_key: "$secret_access_key"
  bucket: factor-ui
  local_dir: dist
  skip_cleanup: true
  on:
    branch: master
- provider: npm
  email: "$email"
  api_key: "$api_key"
  on:
    branch: master
  skip_cleanup: true
env:
  global:
  - secure: SebsYFVB/1/thugeIR01VpFAk8ZLrIygjouOQzuQt5dpYffUAE4Jpc8LWGv7bCQgc6fokpDu2sKkNKrs+C97gvOCnQ+Bv5LtLqe2aT0rBEDJrEM9A3TYK3EEDI6mTOSoSG9L4Q+Zg4dJkjFcMSi9ZxU7tHSUHSl8j2Si3/oACKeYWvRJQquHMMH843mlEQX0HOp1XnX1j8Azh0lzccqJcZyzNnRGL7FexFJCjVCEY9h3v2dYxBn6AyuUfYKEP3AmD0jXTmKTiJtidaw5JCb4rPRbV0bA1Soa4BfadOGeiVBAsqZewyIunIWvV9p8gM7sf4pddO7eVh6HRPh+t7LO3jMvxnsyBIHF8XgIndpb+Xk/q6GAnDQKo/FtslcFpnCvo5gK+n367yyrFRBbLOxmhuJtIor04aXAeivxVuepTo1h28ldfyEp9iNQ5TXTEucMPTzXU23TNejP2BauR5K+f/RQocZQLKC+Zd2dG0WdRILn7YuwW4DACemuszD/3obDdnamHxEbOsKKUDlXq9a8F8YQpcrNR9lZ+hUo/AsmK1qxjPuoYf4cZ9N5Lycs6/jjkgNBR67w+YOrF8YznLXgUY5U3O1XHsYRjsCthlK1CzLmFO6D2qkcFXWqn5RSxCAXxxoIL+VrHsFX4rwjbJhmetoiP/OhI1Wwh8HS0x9bxFA=
  - secure: HnsDxA7TxKn9jOS52Taad5CHmSflCIpcPTaWiDjlgsUUxdApVwgfcGWkGIxLbtPAyZaAy1h1C1/+NNB2ccF7xpvf2C23MqRWdh6a17NHqTl0f0iSI2N/oEvJYFoZSzjCJJIggulSevfJZF9MrRhdBMT2hU2wAy1oY3FRQr5pmML5JdSIls+RmBYnTmsNb7WK1UJb4wl/lpqiYqMYoemRw/ZvCWsxgBV14bEgU7JfnoJC1BoD4PSNtrJorzpLLPas/ZkNr1XzxcsMJcXM2eysowdl4d4n6jjWA9r+fcyHpNE/N7wfvXtz47fxBdaPQbYPa+ivJ8kOKh4Ve+pXf4XE1YzkprECfMknbFLBGT5Ci/XZnWKqYdG+hzgn12dekjYBvd63XxwWDdLJJZ3lW4pvsM7Ht/0secpgzyw35XkjJH1/iFPABJ0xEjT42MMG12HPUnRhVk5BSQYC201Ftjc2Rzy9+DhanTE7nvyElwllhklbiC7BCnUzq+R8wKmVJ0iX9/hxfqZkxZ6uuqVWJzA+Q1ta447bHD2a3WkjOcFpcawFjzL4km2FjI+Im+uWLbFltO9Ppu3vvWp0Ap6pcBqtDJK8klOw84OooSh+xoIbvGf/R6mkZVnXFOVTpAi2KzEsS/u4wmKyl9Thy5a0WvN7BuiCgQchqohcfst/XMI9HDk=
  - secure: NmZM2Q+gWTET0JBbXR3mWAjjBus8jwXdJp8MPl6YxjwYXAsBxDHf0qfmtTiF5+OwnWj3Q+FO1Yr9HFWbRl1yr6s1fL42Jn25gQI8Su8hIZxus10itbIWlMRUejQjX+0Yj9uRREf6AzFp/CfRVnYSs+ctxJqKsyGTuBuSrNz7E4KkqEZuBM4lhVjSExJjcZiGlv3Dl87ADtzCkO4SzJYUxgTc11uPqESgmoB6Tk2P2lR7oHCh0lQ72eqgrXyifTOmKoMsDafal1J7Nf+hcKTEZ+7udZspAerVJudrvPFJteX/1uyi62GgP8LJa8RdqdFLChU9Axe1bm2IuzfEBNsnSKsiH5WYMugA2KDDHSlWbYSMSFtWWMOuhITnjOTNfGP+ertxPn3tblFD8IuPTKcODr4jw04NqLth4JDPkB5P9COU6AHhqPtwNqvVuB+kJ5jpL/PXybneX7uUsOnA3IdY6Tnq2RVQGrUcS/IKHxycZT/tCs+dZPNOGS03K721qGnuYJQW551OMsbfyrqumdQwmOfMKIVB2hHVtCcdaClnQBhRj6AUF4QAXKiQ7HyTI9YwmtMkbKBvr9ctMLGcablskeRB+UAW83kpGPOvYnIHjlvAHejI+wNziCV5b044lZO2dwK8DfFII/PlvW4rduprbxUwpSKfSANfxx6rPhjSgQc=
  - secure: ZmNSXTJxIK9pi5Pz8+1xYbd9FzUMgHgfrhhCi6JASj3ptoiCh07rwjLPE63xm3zLLgjl67qKo64QTNHZPD1VY604rcYS2ewApZc9Mss5ovrHfA5hPPLPbErOwAOfQBNc+3btbVdDVvNGtwfro1yzFdJ3d8ijb61rnymc+eFC+81dXqVq+qgxNGKl+nCYcYv3B4GMjcEdV+iIjDhl/LvxD4W4eb49R3bZz+S/t/o0x46BtVK9servfgjxZqzzfs0hszof0Oo0JMCa8bdKm5RzwIRo3pBphwR7UkFr9GGoDBuSnmT1W9Mazy2qsqc56lYmNcj1cf3t1mhLkPV3FZJctgjix72Dy3aCfJijFOSdREwGQXumSZQiEFLhegiNb9h9fjIrkIdVYG3a8U05hKnxkR2Ye7p2kiO2ZKoB+COJtPBa+XHr/9Ty9p1nJ3FttpeXWWQaKLCa5ikCxTBk8h1QKON75xpMuAuo96QMFqnEa0bV8ccEy9soAKSuSRY0LqR+ktPq+sX/UI+C/4S2B9Beixtl4EO8xRgUK8HgC9bhydTfNlPH2N6FvhDir3fGy2ngG6CfDtgBbLVxqe9aJpqslcQhtcityAKA0p4xm8vzPCb4ZtEEpZaZX+q6J+xpjX5g1JvroP56Uo3xS12l4D1NH9Rcv5PTOGFF7VS7TNL9O9Q=
